I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 102, in script
    "Harvard":
ScriptError: could not find label 'outOfWay'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 102, in script
    "Harvard":
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1697, in execute
    rv = renpy.game.script.lookup(target)
  File "/Applications/renpy-7.3.5-sdk/renpy/script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'outOfWay'.

Darwin-19.4.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Demo 1.0
Tue May 26 21:28:41 2020
